# Generated by Django 2.2 on 2019-04-28 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_administrator_analit_devops_productowner_programmer_teamlid_tester'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammerRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_awerage', models.IntegerField(verbose_name='Покрытие тестами')),
                ('ended_task', models.IntegerField(verbose_name='Закрытых задач')),
                ('returned_task', models.IntegerField(verbose_name='Возвращенных задач от QA')),
                ('pep8', models.IntegerField(verbose_name='Следование стандартам кода')),
                ('stendap', models.IntegerField(verbose_name='Участие в стендапах')),
                ('awerage_team_rate', models.IntegerField(verbose_name='Уcредненная оценка коллегами')),
                ('date', models.DateField(verbose_name='Дата оценки')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Programmer', verbose_name='Участник')),
            ],
        ),
    ]
